Sprint 11
KirillShakurov/ImageFeed pull request #4
Opened 2023-01-10 13:21 UTC by KirillShakurov

Задание 11 спринта на проверку

2023-01-10 21:25 UTC, IBDesignable requested changes

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +                    self.fetchProfile(token: storageToken.token!)
полученный токен можно возвращать в качестве result строкой, и распаковав result свитчом на success/failure можно будет избежать лишнего кода (result get) и force unwrap здесь.

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +        UIApplication.shared.windows.first?.makeKeyAndVisible()
рано для перехода на таббар, ведь токен еще не получили. Критическая ошибка, давай делать переходы между экранами когда будем уверены что необходимые данные получены или получилась ошибка

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +                break
лишний брейк

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +                UIBlockingProgressHUD.dismiss()
кажется независимо от результата - вызвать надо одну строчку. 

Поэтому либо какой-то из важный пункт флоу пропущен, либо избыточный свитч

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                completion(.failure(error))
не стоит ли занулять в случае ошибки тоже? я бы спустила self?.task = nil ниже под свитч

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +                    UIBlockingProgressHUD.dismiss()
в этом случае рано закрывать HUD, есть еще еще запрос профиля.

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +                    self.fetchProfile(token: storageToken.token!)
а вижу, и так отдаешь строчкой токен. 

Поэтому да, давай от do-catch избавимся, и сделаем распаковку через switch result

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +        profileImageView.tag = 1
а зачем теги? можно ли обойтись без этого?

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +        let viewImage = view.viewWithTag(1) as! UIImageView
использование тегов делает код запутанным, пожалуйста, забудь про существование этого метода, пока вот прям действительно не будет способа сделать без них. 
Можно сохранить ссылку на картинку в классе и обращаться сразу к нему, без форс операций

обязательно поправить этот форс каст

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Services/ProfileImageService.swift
> +                completion(.success(self.avatarURL!))
давай перепишем на безопасное извлечение опционала

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Splash/SplashViewController.swift
> +                    self.profileImageService.fetchProfileImageURL(username: (self.profileService.profile?.username)!) { _ in
обязательно распаковать юзернейм

2023-01-10 21:25 UTC, IBDesignable commented on ImageFeed/Splash/SplashViewController.swift
> +                        preferredStyle: .alert)
давай сделаем текста по ТЗ чеклиста

2023-01-13 16:36 UTC, IBDesignable requested changes

2023-01-13 16:36 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +                UIApplication.shared.windows.first?.makeKeyAndVisible()
даже если ошибка, все равно на таббар делаем переход? Кажется это неверно. И давай ответственность отдадим SplashViewcControlller'у, связь через делегат сделаем

2023-01-13 16:36 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
>                      self.fetchProfile(token: storageToken.token!)
Все еще небезопасно, выше же есть распакованный токен (data)

2023-01-13 16:36 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +                    print("Error:", error)
Место где надо бы показать алерт и предложить еще раз авторизоваться. 

Предлагаю тоже сообщить об ошибке сплеш-скрину, пусть покажет сообщение

2023-01-13 16:36 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +                UIBlockingProgressHUD.dismiss()
в случае успеха UIBlockingProgressHUD.dismiss() - закроет лоадер, и дальше запрос на профиль будет делаться на разблокированном экране. Это не хорошо. Надо дождаться завершения последовательности запроса.

2023-01-16 17:48 UTC, KirillShakurov commented on ImageFeed/Auth/AuthViewController.swift
>                      self.fetchProfile(token: storageToken.token!)
не понимаю, как это исправить

2023-01-17 20:37 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
>                      self.fetchProfile(token: storageToken.token!)
self.fetchProfile(token: data)

2023-01-22 16:27 UTC, merged